markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: ""



title: FHP Startups

version: 2.3.1

github:
  repo: https://github.com/NETZPULSEN/fhp-startups